---
  - name: Upload tar.gz Elasticsearch from remote URL
    get_url:
      url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
      dest: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
      mode: 0755
      timeout: 60
      force: true
    register: get_elastic
    until: get_elastic is succeeded
    tags: elastic
  - name: Create directrory for Elasticsearch
    file:
      state: directory
      path: "{{ elastic_home }}"
    tags: elastic
  - name: Extract Elasticsearch in the installation directory
    become: true
    unarchive:
      copy: false
      src: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
      dest: "{{ elastic_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ elastic_home }}/bin/elasticsearch"
    tags:
      - skip_ansible_lint
      - elastic
  - name: Set environment Elastic
    become: yes
    template:
      src: templates/elk.sh.j2
      dest: /etc/profile.d/elk.sh
    tags: elastic