version: '3'
services:
  centos7:
    image: pycontribs/centos:7
    container_name: centos7
    restart: unless-stopped
    entrypoint: "sleep infinity"

  ubuntu:
    image: pycontribs/ubuntu
    container_name: ubuntu
    restart: unless-stopped
    entrypoint: "sleep infinity"

  fedora:
    image: pycontribs/fedora
    container_name: fedora
    restart: unless-stopped
    entrypoint: "sleep infinity"
