---
  - name: Install Java
    hosts: all
    tasks:
      - name: Set facts for Java 8 vars
        set_fact:
          java_home: /opt/jdk/{{ java_jdk_version }}
        tags: java
      - name: Upload .tar.gz file containing binaries from local storage
        copy:
          src: "{{ java_oracle_jdk_package }}"
          dest: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
        register: download_java_binaries
        until: download_java_binaries is succeeded
        tags: java
      - name: Ensure installation dir exists
        become: true
        file:
          state: directory
          path: "{{ java_home }}"
        tags: java
      - name: Extract java in the installation directory
        become: true
        unarchive:
          copy: false
          src: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
          dest: "{{ java_home }}"
          extra_opts: [--strip-components=1]
          creates: "{{ java_home }}/bin/java"
        tags:
          - skip_ansible_lint
          - java
      - name: Java | Export environment variables
        become: true
        template:
          src: jdk.sh.j2
          dest: /etc/profile.d/jdk.sh
        tags: java