version: "3"
services:
  teamcity:
    image: jetbrains/teamcity-server
    volumes:
      - ~/teamcity/data/:/data/teamcity_server/datadir
      - ~/teamcity/logs/:/opt/teamcity/logs
    ports:
      - 8111:8111
  teamcity-agent:
    image: jetbrains/teamcity-agent 
    depends_on:
      - teamcity
    volumes:
      - ~/teamcity/agent/:/data/teamcity_agent/conf 
    environment:
      SERVER_URL: "http://teamcity:8111"